"""Initial schema for the Agent Library.

Creates all nine tables with the indexes the search endpoint relies on:
users, tags, wgt_counters, assets, activity_log, config_settings, asset_tags,
asset_versions, asset_files.

MySQL specifics
---------------
* Every table is created with InnoDB (row-level locking is what makes the
  ``SELECT ... FOR UPDATE`` in app/wgt.py serialise concurrent WGT allocation)
  and utf8mb4 (real four-byte Unicode, so an emoji in a description does not
  truncate a row).
* ``BigInteger().with_variant(Integer, "sqlite")`` renders as ``BIGINT`` on
  MySQL and ``INTEGER`` on SQLite, so the same migration runs under the test
  suite and in production.
* ``sa.JSON`` renders as MySQL's native ``JSON`` column type.

Apply with::

    FLASK_APP=wsgi.py flask db upgrade

Roll back one revision with::

    FLASK_APP=wsgi.py flask db downgrade -1

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-20

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('wgt_counters',
    sa.Column('department_digit', sa.String(length=8), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('department_digit'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('activity_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('actor_email', sa.String(length=254), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=True),
    sa.Column('object_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('object_label', sa.String(length=200), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_activity_object', ['object_type', 'object_id'], unique=False)
        batch_op.create_index('ix_activity_ts_action', ['ts', 'action'], unique=False)

    op.create_table('assets',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('wgt_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('use_case', sa.Text(), nullable=False),
    sa.Column('problem_solved', sa.Text(), nullable=True),
    sa.Column('input_requirements', sa.Text(), nullable=True),
    sa.Column('expected_output', sa.Text(), nullable=True),
    sa.Column('example_use', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('creator_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('owner_name', sa.String(length=160), nullable=False),
    sa.Column('owner_email', sa.String(length=254), nullable=False),
    sa.Column('creator_name', sa.String(length=160), nullable=False),
    sa.Column('backup_owner', sa.String(length=160), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=160), nullable=False),
    sa.Column('intended_audience', sa.String(length=48), nullable=False),
    sa.Column('access_level', sa.String(length=48), nullable=False),
    sa.Column('sensitivity', sa.String(length=48), nullable=False),
    sa.Column('review_frequency', sa.String(length=48), nullable=False),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('current_version', sa.String(length=16), nullable=False),
    sa.Column('direct_url', sa.String(length=2048), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('additional_departments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_featured'), ['featured'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_last_updated_at'), ['last_updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_next_review_date'), ['next_review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)
        batch_op.create_index('ix_assets_status_department', ['status', 'department'], unique=False)
        batch_op.create_index('ix_assets_status_type', ['status', 'asset_type'], unique=False)
        batch_op.create_index('ix_assets_status_updated', ['status', 'last_updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_wgt_code'), ['wgt_code'], unique=True)

    op.create_table('config_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    op.create_table('asset_tags',
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id', 'tag_id'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_tags_tag_id'), ['tag_id'], unique=False)

    op.create_table('asset_versions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('version_number', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('updated_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by_name', sa.String(length=160), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('instructions_snapshot', sa.Text(), nullable=True),
    sa.Column('configuration_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'version_number', name='uq_asset_version_number'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.create_index('ix_asset_versions_asset_current', ['asset_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_versions_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_versions_created_at'), ['created_at'], unique=False)

    op.create_table('asset_files',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('asset_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('asset_version_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=64), nullable=False),
    sa.Column('relative_path', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=True),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('scan_status', sa.String(length=16), nullable=False),
    sa.Column('uploaded_by_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_version_id'], ['asset_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci'
    )
    with op.batch_alter_table('asset_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_files_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_files_asset_version_id'), ['asset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_files_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_files_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_files_stored_name'), ['stored_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_files_stored_name'))
        batch_op.drop_index(batch_op.f('ix_asset_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_asset_files_kind'))
        batch_op.drop_index(batch_op.f('ix_asset_files_created_at'))
        batch_op.drop_index(batch_op.f('ix_asset_files_asset_version_id'))
        batch_op.drop_index(batch_op.f('ix_asset_files_asset_id'))

    op.drop_table('asset_files')
    with op.batch_alter_table('asset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_asset_versions_asset_id'))
        batch_op.drop_index('ix_asset_versions_asset_current')

    op.drop_table('asset_versions')
    with op.batch_alter_table('asset_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_tags_tag_id'))

    op.drop_table('asset_tags')
    op.drop_table('config_settings')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_wgt_code'))
        batch_op.drop_index('ix_assets_status_updated')
        batch_op.drop_index('ix_assets_status_type')
        batch_op.drop_index('ix_assets_status_department')
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_platform'))
        batch_op.drop_index(batch_op.f('ix_assets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_assets_next_review_date'))
        batch_op.drop_index(batch_op.f('ix_assets_name'))
        batch_op.drop_index(batch_op.f('ix_assets_last_updated_at'))
        batch_op.drop_index(batch_op.f('ix_assets_featured'))
        batch_op.drop_index(batch_op.f('ix_assets_department'))
        batch_op.drop_index(batch_op.f('ix_assets_creator_id'))
        batch_op.drop_index(batch_op.f('ix_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_ts_action')
        batch_op.drop_index('ix_activity_object')
        batch_op.drop_index(batch_op.f('ix_activity_log_ts'))
        batch_op.drop_index(batch_op.f('ix_activity_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action'))

    op.drop_table('activity_log')
    op.drop_table('wgt_counters')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    # ### end Alembic commands ###
